-- first switch to the database - esb, then run the following commands

-- user table
create table IF NOT EXISTS Users(
	Username text primary key,
	UserPassword text not null,
	UserRole text not null,
	UserPriority int not null
)

-- users waiting for confirmation after signup from the admin
create table IF NOT EXISTS SignupConfirmation(
	Username text primary key,
	UserPassword text not null,
	UserRole text not null
)


-- logs for each request
create table IF NOT EXISTS AckLogs(
	RequestID text not null, -- to be generated by the HTTP server
	Username text not null, -- username of the user
	TypeofRequest text not null, -- API Call / Client to client communication
	Receiver text not null, -- API name / Receiver client
	RequestPayload text not null, -- if text then include, for file transfer use the file name
	InitialTimestamp timestamp not null, -- time when request arrives at the HTTP server from a user client
	FinalTimestamp timestamp not null, -- time when the request response arrives at HTTP server to be sent back to the user client
	ServiceResponseStatus int not null, -- API call status, etc.
	ReturnResponseStatus int not null -- Successfully sent back to the user client or not
)